blog/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from core.views import main_view
import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('<str:ref_code>', main_view, name='main-view'),
    path('', main_view, name='main-view'),
 #   path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
   # path('mom/', include(('core.urls', ''), namespace='core')),

]

from django.conf import settings
from django.views.static import serve
from django.urls import include, re_path

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

#handler404 = 'core.views.entry_not_found'
#handler500 = 'entry_not_found'

'''if settings.DEBUG == False:
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    pass'''

core/urls.py
from argparse import Action
from django.urls import path
from . import views

from .views import HomeView, PostView,PostCreateViews, PostCreateView, PostUpdateView, PostDeleteView, viewView,View,Postsee,Reco
#HomeView,
urlpatterns = [
    path('users/profile/<str:string>/cashout',views.cash,name='cashout'),

    path('',views.sample , name='home'),
    path('posts',HomeView.as_view() , name='posts'),
    path('tutor/<str:code>/',views.tutor,name='tutor'),
    path('search12',views.search12,name=' search12 '),
    path('post/created/', PostCreateViews.as_view(), name='post_c'),
    path('tutor/<str:str>/save',views.videos,name='save'),
    path('post/<pk>',Reco.as_view(),name='recos'),
    path('post/<int:ints>/<str:str1>/<int:int2>/<int:com>/', views.sat, name='sat'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('views', viewView.as_view(), name='views'),
    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/<pk>/<p>/', Postsee.as_view(), name='see'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('submit', views.search, name='submit'),
    path('bus', views.sow, name='bus'),
    path('add', View.as_view(), name='add'),
    path('test', views.test, name='test'),
    path('bbb', views.action,name='bbb'),
    path('email', views.Email,name='email'),
    path('admin', views.Admin,name='admin'),
    path('code',views.save_code,name='code'),
    path('date',views.date,name='date'),
    path('location',views.location,name='location'),
    path('reco',views.reco,name='reco'),
    path('recomend',views.reco_search,name='recomend'),
    path('reload',views.run,name='reload'),
    path('sug',views.sug,name='sug'),
    path('users/signup/terms',views.terms,name='terms'),
   # path('class/<int:id>/',views.classes,name='class'),
    #path('vote/<int:id>/',views.vote,name='vote'),
  #  path('submit_camp',views.camps,name='submit_camp'),
    path('<username>',views.category2, name='category2'),
    path('<username>',views.category, name='category'),
    path('<username>/',views.category3, name='category3'),
    path('post/<username>/',views.profile, name='profile'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView
)
from django.urls import reverse_lazy

from .views import signup, log_in, log_out, profile, edit_profile
#from users.views import ResetPasswordView
from . import views


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<username>/', profile, name='profile'),
    path('edit-profile/', edit_profile, name='edit_profile'),
  #  path('/users/profile/23434553c/cash',views.cash, name='cash'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        success_url='/users/password_reset/done/'),
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url='/users/reset/done/'),
        name='password_reset_confirm'
    ),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

core/models.py
from email.policy import default
from django.db import models
from django.conf import settings
from datetime import datetime


v = datetime.today().strftime('%Y-%m-%d')

class Tag(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    author = models.ForeignKey(
    settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to='media/', blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now_add=True)
    country = models.TextField(default='country')
    province = models.TextField(default='province')
    place = models.TextField(default='place')
    school = models.TextField(default='school')
    grade = models.TextField(default='school')
    attendance = models.TextField(default='False')
    sub = models.TextField(default='sub')
    topic = models.TextField(default='topic')
    username = models.TextField(default='username')


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    image = models.ImageField(upload_to='pop',blank=True, null=True)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    numbers = models.IntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

class invites(models.Model):
    user_mail = models.TextField(default ='N/A')
    inviter_mail = models.EmailField(max_length=100)

from django.contrib.auth.models import User


class code(models.Model):
    email = models.EmailField(max_length=100)
    code = models.TextField(default='N/A')

class details(models.Model):
    email = models.EmailField(max_length=100)
    visit = models.ImageField(default='N/A')

class worker(models.Model):
    email = models.EmailField(max_length=100)
    true_fasle = models.TextField(default='F')


class paycheck(models.Model):
    reciver = models.TextField(default='N/A')
    money = models.TextField(default='0.0')
    true_fasle = models.TextField(default='F')


class place(models.Model):
    country = models.TextField(default='country')
    province = models.TextField(default='province')
    place = models.TextField(default='place')
    school = models.TextField(default='school')
    grade = models.TextField(default='grade')
    email = models.IntegerField(default=0)

class others(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    author = models.IntegerField(default=0)
    content = models.TextField()
    image = models.ImageField(upload_to='', blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now_add=True)
    id2 = models.IntegerField(default=0)
    sub = models.TextField(default='sub')
    topic = models.TextField(default='topic')
   # ctime = models.DateTimeField(auto_now_add=True, default=datetime.now())
    #uptime = models.DateTimeField(auto_now=True, default=datetime.now())   
class validate(models.Model):
    com = models.IntegerField(default=0)

class camp(models.Model):
    level = models.TextField(default="text")
    subject = models.TextField(default="text")
    votes = models.IntegerField(default=0)
    grade = models.TextField(default="text")
    description = models.TextField(default="des")
    language = models.TextField(default="en")
    author = models.TextField(default="author")
    code = models.TextField(default="code")
    
class usercamp(models.Model):
    camp_id = models.IntegerField(default=0)
    email = models.TextField(default="email")
    level = models.TextField(default="text")
    subject = models.TextField(default="text")
    votes = models.IntegerField(default=0)
    grade = models.TextField(default="text")
    description = models.TextField(default="des")
    language = models.TextField(default="en")
    author = models.TextField(default="author")
    
class campvedios(models.Model):
    vedio = models.FileField(upload_to='', blank=True, null=True)
    camp_id = models.IntegerField(default=0)

class comemnts_camp(models.Model):
    content = models.TextField(default="text")
    camp_id = models.IntegerField(default=0)

    
    
    
    
    
    
    

    
    

users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField('email address',unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["username"]
    is_verified = models.BooleanField(default=False)
    number = models.IntegerField(default=000000000000)
    phone = models.BigIntegerField(default=0000000000000 )

class Profile(models.Model):
    about_me = models.TextField()
    image = models.ImageField(upload_to='profile_image', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.TextField(default='N/A')
    number = models.IntegerField(default=000000000000)
    phone = models.IntegerField(default=0000000000000)


    def __str__(self):
        return self.user.username

class workers(models.Model):
    email = models.EmailField(max_length=100)

core/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content','image')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","email")
#"email"

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField()


class EditProfileForm(forms.Form):
    username = forms.CharField()
    about_me = forms.CharField(widget=forms.Textarea())
    image = forms.ImageField(required=False)

    def __init__(self, original_username, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_username = original_username

    def clean_username(self):
        """
        This function throws an exception if the username has already been 
        taken by another user
        """

        username = self.cleaned_data['username']
        if username != self.original_username:
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError(
                    'A user with that username already exists.')
        return username

users/views.py
import email
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from core.models import paycheck, worker
from .models import User, Profile
from .forms import SignUpForm, LoginForm, EditProfileForm
from core.models import invites


def signup(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
    #    is_private = request.GET['full_name']


        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request, "Congratulations, you are now a registered user!")
            is_private = request.POST['is_private']
            is_privates = request.POST['PHONE']
            is_invite = request.POST['inviter']

            try:
             save_ = invites(user_mail=is_invite,inviter_mail=is_invite)
             save_.save()
            except:
                pass
                
            try:
             numbers = User.objects.get(id=request.user.id)
             numbers.number = is_private
             numbers.phone = is_privates
             numbers.save()
            except:
                pass
            #return render('http://127.0.0.1/')
        else:
             form = SignUpForm()
          #   messages.success(request, "")
             messages.success(request, 'Username is already taken.')
             mess = 'Change username or password.'
             return render(request, 'users/signup.html', {'form': form})
             
        return redirect('core:home')

    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def log_in(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
         email = form.cleaned_data["email"]
         password = form.cleaned_data["password"]
         if "@" in email:
            email = form.cleaned_data["email"]  
             # print(email)1wwwwwwwwwwwwwwws
            password = form.cleaned_data["password"]
            # We check if the data is correct
            user = authenticate(email=email, password=password)
            if user:  # If the returned object is not None
                login(request, user)  # we connect the user
                return redirect('core:home')
            else:  # otherwise an error will be displayed
                messages.error(request, 'Invalid email or password')
         else:
            # is_privates = request.POST['email']
          #   password2 = request.POST['password']
            user = authenticate(email=email+'@gmail.com', password=password)
           # print('mmmmuuu')
            if user:  # If the returned object is not None
                login(request, user)  # we connect the user
                return redirect('core:home')
        else:
         print('ggggggg')
    else:
     form = LoginForm()
    messages.error(request, 'Log in with valid credentials')
    return render(request, 'users/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect(reverse('users:login'))


@login_required
def profile(request, username):
    current_user = request.user.email
    number = invites.objects.filter(inviter_mail=request.user.email).count()
    print(number)
    if worker.objects.filter(email=current_user).exists():
        wages = paycheck.objects.get(reciver=current_user)
        pass_wages = wages.money
        money = float(pass_wages)
        two = round(money,3)
        name = 'welcome worker'
    else:
        two = ''
        name = ''
   
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user) 
    return render(request, 'users/profile.html', {'profile': profile,'invites':number, 'user': user,'wage':two,'name':name})

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.user.username,
                               request.POST, request.FILES)
        if form.is_valid():
            about_me = form.cleaned_data["about_me"]
            username = form.cleaned_data["username"]
            image = form.cleaned_data["image"]

            user = User.objects.get(id=request.user.id)
            profile = Profile.objects.get(user=user)
            user.username = username
            user.save()
            profile.about_me = about_me
            if image:
                profile.image = image
            profile.save()
            return redirect("users:profile", username=user.username)
    else:
        form = EditProfileForm(request.user.username)
    return render(request, "users/edit_profile.html", {'form': form})

templates/core/post_form.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="title" content="Ask online Form">
  <meta name="description" content="The Ask is a bootstrap design help desk, support forum website template coded and designed with bootstrap Design, Bootstrap, HTML5 and CSS. Ask ideal for wiki sites, knowledge base sites, support forum sites">
  <meta name="keywords" content="HTML, CSS, JavaScript,Bootstrap,js,Forum,webstagram ,webdesign ,website ,web ,webdesigner ,webdevelopment">
  <meta name="robots" content="index, nofollow">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="English">
  <title>Ask Me</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=AM_CHTML"></script>
  <link href="{% static 'css/editor.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"> </head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>

    .content-box {
      height: 550px;
      padding: 20px;
      border: 2px solid black;
      width: 90%;
      display: flex;
      align-self: flex-end;


    }

    .card-img-top{
      display: none;
  }

  .card {
    height:300px;
    width:680px;
    border: 1px solid red;

  }

  .ques-details10018 {
    margin-top: 10px;
     overflow: hidden;
     -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
     display: -webkit-box;
     -webkit-line-clamp: unset;
     -webkit-box-orient: vertical;
 }

 
 .overlay {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  /*background-color: rgb(0,0,0);
  background-color: rgba(0,0,0, 0.9);*/
  background-color:white;
  overflow-x: hidden;
  transition: 0.5s;
}

.overlay-content {
  position: relative;
  top: 25%;
  width: 100%;
  text-align: center;
  margin-top: 30px;
}

.overlay a {
  padding: 8px;
  text-decoration: none;
  font-size: 36px;
  color: black;
  display: block;
  transition: 0.3s;
}

.overlay a:hover, .overlay a:focus {
  color: #f1f1f1;
}

.overlay .closebtn {
  position: absolute;
  top: 20px;
  right: 45px;
  font-size: 60px;
}
  </style>
<script>
function op(){
  
  var currentLocation = window.location.href;
   console.log(currentLocation)
   if (currentLocation.includes("created")){
    document.getElementById('id_content').style.display = 'none';
    document.getElementById('text2').style.display = 'none';

  } else {
 
}
}


  function openNav() {
    document.getElementById("myNav").style.width = "100%";
  }
  
  function closeNav() {
    document.getElementById("myNav").style.width = "0%";
  }

</script>
<body onload="op()">
  <div class="top-menu-bottom932">
    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="fa fa-graduation-cap" style="font-size:80px; color:white;" href="#">Ask?</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav"> </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/">Home</a></li>
                    <li><a href="{% url 'core:views' %}"> Questions </a></li>
                   
                    <li><div class="dropdown">
                      {% if bell.count > 0 %}
                      <p onclick="myFunction()" class="notification"> <span>Solutions</span> <span class="badge">{{bell.count}}</span> </p>
                      {% else %}
                      <p onclick="myFunction()" class="notification"> <span>Solutions</span> <span class="badge"></span> </p>
                      {% endif %}
                      <div id="myDropdown" class="dropdown-content">
                        {% for i in bell %}
                        <a href="{% url 'core:see' i.verb i.id  %}">{{i.description}}</a>
                        {% endfor %}
                      </div>
                    </div></li>
                    {% if request.user.is_authenticated %}
                    <li> 
                      <li><a href=" {% url 'users:logout' %} " >Log Out</a></li>
                    </li>
                    <li> 
                      <li><a href="{% url 'users:profile' request.user.username %}  " >Profile</a></li>
                    </li>
                    <li> 
                    </li>
                    <li> 
                    </li>
                    {% if request.user.is_superuser %}
                    <li> 
                      <li><a href="admin" >Admin </a></li>
                    </li>

                    {% else %}
                    {% endif %}
                    <li> 
                    </li>
                    {% if count > 2 %}
                    <li> 
                      <li><a href="" onclick="warn()">Ask Question</a></li>
                    </li>
                    {% else %}
                    <li> 
                      <li><a href="{% url 'core:post_create' %}  " >Ask Question</a></li>
                    </li>
                    {% endif %}
                    {% else %}
                    <li> 
                      <li><a href=" {% url 'users:login' %}  " >Log In</a></li>
                    </li>
                    <li> 
                      <li><a href=" {% url 'users:signup' %} " >Sign Up</a></li>
                    </li>
                    
                    {% endif %}

                        <ul class="dropdown-menu animated zoomIn">
                            
                        </ul>
                    </li>
                   
                        <ul class="dropdown-menu animated zoomIn">
                        </ul>
                    </li>
                        <ul class="dropdown-menu animated zoomIn">
                            <li><a href="logIn.html">Login</a></li>
                            
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>


<style>
  .footer {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  background-color: #efefef;
  text-align: center;
}
  </style>
  <div class="container">
    <div class="row">
      <div class="col-8 offset-2">
        {{v}}
        <p></p>
        <h2 class=" my-5">Ask Questions</h2>
      
        <form method="post" enctype="multipart/form-data" name="myForm">
          {% csrf_token %}
  
          <!--<div class="form-group"> onsubmit="return validateForm()" 
            <p>Grade</p>
            <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="id_title"
              placeholder="Grade" name="title" value='{{ form.title.value|default:"" }}'>
            {% if form.title.errors %}
            <div class="invalid-feedback">{{ form.title.errors }}</div>
            {% endif %}
          </div>-->
          <select name="sub" id="myselect">
            <option value="Maths">Maths</option>
            <option value="Life Science">Life science</option>
            <option value="Physics">Physics</option>
            <option value="Natural Science">Natural Science</option>
            <option value="Geography">Geography</option>
            <option value="Maths Literacy">Maths Literacy</option>
            <option value="Technology">Technology</option>
            <option value="Accounting">Accounting</option>
            <option value="EMS">EMS</option>
            <option value="Nursing">Nursing</option>
            <option value="Music">Music</option>
            <option value="Medical">Medical</option>
            <option value="Economics">Economics</option>
            <option value="Law">Law</option>
            <option value="Chemistry">Chemistry</option>
            <option value="Education">Education</option>
            <option value="Engineering">Engineering</option>
            <option value="Psychology">Psychology</option>
            <option value="Pharmacy">Pharmacy</option>
            <option value="Business">Business Administration</option>
            <option value="Statistics">Statistics</option>
            <option value="Art">Art</option>
            <option value="Computer Science">Computer Science</option>
            <option value="Accounting">Accounting</option>
            <option value="Architecture">Architecture</option>
            <option value="Hospitality ">Hospitality </option>
            <option value="Finance">Finance</option>
            <option value="Agriculture">Agriculture</option>
            <option value="Other">Other</option>
            <option value="Journalism and Mass Communication">Journalism and Mass Communication</option>
          </select>

          <select name="title" id="myselect">
            <option value="Grade4">Grade 4</option>
            <option value="Grade5">Grade 5</option>
            <option value="Grade6">Grade 6</option>
            <option value="Grade7">Grade 7</option>
            <option value="Grade8">Grade 8</option>
            <option value="Grade9">Grade 9</option>
            <option value="Grade10">Grade 10</option>
            <option value="Grade11">Grade 11</option>
            <option value="Grade12">Grade 12</option>
            <option value="Tetiary">Tetiary</option> 
            <option value="Other">Other</option> 
          </select>
        <!--  <a href="{% url 'core:add' %}" class="">Test equation</a>
          <button class="" onclick="check()">Backticks</button><br>
          <div class="form-group"><br><br>
            <input type="text" class="form-control {% if form.topic.errors %}is-invalid{% endif %}" id="id_title"
              placeholder="Topic or description" name="topic" value=''>
            {% if form.topic.errors %}
            <div class="invalid-feedback">{{ form.topic.errors }}</div>
            {% endif %}
          </div>
        -->
        <br>
          <div class="form-group">
            <br>
            <p id="text2">Statement and Question </p>
            <textarea type="text" class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
              name="content" cols="150" rows="5">{{ form.content.value|default:"" }}</textarea>
            {% if form.content.errors %}
            <div class="invalid-feedback">{{ form.content.errors }}</div>
            {% endif %}
          </div>
  
          {{ form.image.label_tag }}
            <input type="file" class="{% if form.image.errors %}is-invalid{% endif %}" id="id_image" name="image"
              accept="image/*">
            {% if form.image.errors %}
            <div class="invalid-feedback">{{ form.image.errors }}</div>
            {% endif %}
          </div>
  
         <!-- <div class="form-group">
            {{ form.tags.label_tag }}<br>
            <select class="custom-select w-25" name="tags" id="id_tags" multiple>
              {% for name, value in form.tags.field.choices %}
              <option value="{{ name }}">{{ value }}</option>
              {% endfor %}
            </select>
            {% if form.tags.errors %}
            <div class="invalid-feedback">{{ form.tags.errors }}</div>
            {% endif %}
          </div>
          <a class='btn btn-primary' onclick="openNav()"> Ask Question ...</a>
          <div id="myNav" class="overlay">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="overlay-content"><br>-->
              <button type="submit" id="submit" class="btn btn-primary">
                {% if update %}Update the post{% else %}Ask Question{% endif %}
              </button>
           <!--</div>
          </div>
         <button type="submit" id="submit" class="btn btn-primary">
            {% if update %}Update the post{% else %}Ask Question{% endif %}
          </button>-->
        </form>
  
      </div>
    </div>
  </div>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/editor.js' %}"></script>
   	<script>
			$(document).ready(function() {
				$("#txtEditor").Editor();
			});
		</script>
  
</body>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<center><div class="foot">
  <h5 style="color:grey;">Copyright 2022. All Rights Reserved.</h5> 
  <h5 style="color:grey;">Ask?.com</h5> 
  <div style="color:grey;">
  </div></center>

</html>

templates/core/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Check if you have loged in</h1>
    <h1>Check if you have filled location</h1>

</body>
</html>
    

templates/core/terms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>




</body>
</html>